services:
  postgres:
    image: postgres:17-alpine
    container_name: cars24-postgres
    environment:
      POSTGRES_USER: cars24
      POSTGRES_PASSWORD: cars24
      POSTGRES_DB: cars24
    ports:
      - "5432:5432"
    volumes:
      - cars24-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cars24 -d cars24"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cars24-pgdata:
